### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by RasmusLindroth** [RasmusLindroth/tut#1]
- [x] Upload media
- [ ] Show errors in UI. Don't log.fatal if you don't have to

- [x] Make it more configurable 

- [x] Change lefpane to a list?

- [x]  Notifications

- [ ] Make use of streams?

- [x] Change visibility options for toots  

- [x] Better default colors. Get from xrdb?

**Comment by nyex** [comment]
Getting the colors from xrdb would make easier the life of those crazy nerds that tend to change color schemes every two days using pywal or something like that ;)

**Comment by RasmusLindroth** [comment]
@nyex  there is support for getting colors from xrdb :)
