### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by RasmusLindroth** [RasmusLindroth/tut#129]
### TODO
- [x] Themes and default style on elements
- [x] Don't use `os.Exit()`, print errors in the UI
- [x] Add config option for the confirmation modal
- [x] Add desktop notifications
- [x] Fix links for item user
- [x] Have a timeout on loading older
- [x] Custom program on links
- [x] Support polls
- [x] Implement selecting the default timeline
- [x] Show help
